# Generated by Django 2.2.5 on 2019-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('stock_price', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
